- hosts: iphone4
  gather_facts: no
  vars_files:
    - secrets.yml
  vars:
    project_name: pysms2email
    entry_file: /var/root/deploys/pysms2email/sms2email.py
    deploy_path: /var/root/deploys
    project_path: /var/root/deploys/pysms2email
    launchctl_path: /Library/LaunchDaemons
  handlers:
    - name: launchctl stop "deploys.{{ project_name }}.monitor"
      command: launchctl stop "deploys.{{ project_name }}.monitor"
    - name: launchctl start "{{ project_name }}"
      command: launchctl start "deploys.{{ project_name }}.monitor"
    - name: launchctl start env
      command: launchctl start deploys.environments.mail
  tasks:
    - name: stop launchctl
      command: launchctl stop "deploys.{{ project_name }}.monitor"
    - name: copy source code
      copy:
        src: ../pysms2email
        dest: "{{ deploy_path }}/"
    - name: chmod +x to file
      command: chmod +x "{{ entry_file }}"
    - name: copy plist environment variable
      template:
        src: ./files/deploys.environments.mail.plist
        dest: "{{ launchctl_path }}/deploys.environments.mail.plist"
    - name: load environment variable
      command: "launchctl load {{ launchctl_path }}/deploys.environments.mail.plist"
      notify: launchctl start env
    - name: update apple launchctl
      template:
        src: "./files/deploys.{{ project_name }}.monitor.plist"
        dest: "{{ launchctl_path }}/deploys.{{ project_name }}.monitor.plist"
    - name: load {{ project_name }} plist
      command: "launchctl load {{ launchctl_path }}/deploys.{{ project_name }}.monitor.plist"
      notify: launchctl start "{{ project_name }}"
