- hosts: iphone4
  gather_facts: no
  vars_files:
    - secrets.yml
  vars:
    entry_file: /var/root/deploys/pysms2email/sms2email.py
    deploy_path: /var/root/deploys
    project_path: /var/root/deploys/pysms2email
    launchctl_path: /Library/LaunchDaemons
  handlers:
    - name: launchctl start pychgoods
      command: launchctl start deploys.pychgoods.monitor
    - name: launchctl stop pychgoods
      command: launchctl stop deploys.pychgoods.monitor
  tasks:
    # - name: stop launchctl
    #   command: launchctl stop deploys.pychgoods.monitor
    - name: copy source code
      copy:
        src: ../pysms2email
        dest: "{{ deploy_path }}/"
    - name: chmod +x to file
      command: chmod +x "{{ entry_file }}"
    - name: set launchctl environment variable
      template:
        src: ./files/envs.sh
        dest: "{{ deploy_path }}/envs.sh"
        mode: "u+x,g+x,o+x"
    - name: copy plist environment variable
      copy:
        src: ./files/deploys.environments.mail.plist
        dest: "{{ launchctl_path }}/deploys.environments.mail.plist"
    - name: load environment variable
      command: "launchctl load {{ launchctl_path }}/deploys.environments.mail.plist"
    # - name: update config
    #   copy:
    #     src: ./files/conf.cfg
    #     dest: "{{ project_path }}/conf.cfg"
    # - name: update apple launchctl
    #   copy:
    #     src: ./files/deploys.pychgoods.monitor.plist
    #     dest: "{{ launchctl_path }}/deploys.pychgoods.monitor.plist"
    # - name: load pychgoods plist
    #   command: "launchctl load {{ launchctl_path }}/deploys.pychgoods.monitor.plist"
    #   notify: launchctl start pychgoods
